"""Build the deployable site: web/ plus one static page per city.

    python scripts/build_site.py --out _site [--base-path /weahist/]

For every place in web/cities.json this writes <out>/<slug>/index.html — the
app shell with its own title, description, canonical URL, structured data and
crawlable text — so search engines can index each city. It also writes a
sitemap.xml listing every page and a 404.html that turns unknown paths into a
?location= search. Standard library only, so CI can run it with plain Python.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import shutil
from datetime import date
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SITE_URL = "https://tnam0x.github.io/weahist/"

# Vietnamese is the indexed language (the UI can switch to English in place).
ROOT_TITLE = "Lịch sử thời tiết & chất lượng không khí | Weather History"
ROOT_DESCRIPTION = (
    "Xem miễn phí lịch sử thời tiết và chất lượng không khí của mọi thành phố: nhiệt độ, "
    "độ ẩm và chỉ số AQI theo giờ hoặc theo ngày, từ 24 giờ qua đến 1 năm."
)
CITY_TITLE = "Thời tiết {place}: lịch sử nhiệt độ, độ ẩm, AQI"
CITY_DESCRIPTION = (
    "Lịch sử thời tiết và chất lượng không khí tại {place}: nhiệt độ, độ ẩm và chỉ số AQI "
    "theo giờ hoặc theo ngày, từ 24 giờ qua đến 1 năm, cập nhật từ Open-Meteo."
)
OG_IMAGE_ALT = "Lịch sử thời tiết: đường nhiệt độ và độ ẩm trên nền các mức chất lượng không khí"

SEO_BLOCK = re.compile(r"<!-- seo:start.*?-->.*?<!-- seo:end -->", re.S)
PAGE_CITY = '<script type="application/json" id="page-city">null</script>'
CITY_INDEX = "<!-- city-index -->"


def place_vi(city: dict[str, Any]) -> str:
    return f"{city['vi']}, {city['country_vi']}"


def seo_block(*, title: str, description: str, url: str, ld: dict[str, Any]) -> str:
    e = html.escape
    image = f"{SITE_URL}og-image.png"
    ld_json = json.dumps(ld, ensure_ascii=False, indent=2).replace("</", "<\\/")
    return f"""<!-- seo:start (generated by scripts/build_site.py) -->
    <title>{e(title)}</title>
    <meta name="description" content="{e(description)}" />
    <link rel="canonical" href="{e(url)}" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Weather History" />
    <meta property="og:title" content="{e(title)}" />
    <meta property="og:description" content="{e(description)}" />
    <meta property="og:url" content="{e(url)}" />
    <meta property="og:image" content="{image}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:alt" content="{e(OG_IMAGE_ALT)}" />
    <meta property="og:locale" content="vi_VN" />
    <meta property="og:locale:alternate" content="en_US" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="{e(title)}" />
    <meta name="twitter:description" content="{e(description)}" />
    <meta name="twitter:image" content="{image}" />
    <script type="application/ld+json">
{ld_json}
    </script>
    <!-- seo:end -->"""


def root_ld() -> dict[str, Any]:
    return {
        "@context": "https://schema.org",
        "@type": "WebApplication",
        "name": "Weather History",
        "alternateName": "Lịch sử Thời tiết",
        "url": SITE_URL,
        "description": ROOT_DESCRIPTION,
        "applicationCategory": "UtilitiesApplication",
        "operatingSystem": "Any",
        "browserRequirements": "Requires JavaScript",
        "inLanguage": ["vi", "en"],
        "isAccessibleForFree": True,
        "image": f"{SITE_URL}og-image.png",
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
        "author": {"@type": "Person", "name": "tnam0x", "url": "https://github.com/tnam0x"},
    }


def city_ld(city: dict[str, Any], title: str, description: str, url: str) -> dict[str, Any]:
    return {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": title,
        "url": url,
        "description": description,
        "inLanguage": "vi",
        "isPartOf": {"@type": "WebSite", "name": "Weather History", "url": SITE_URL},
        "about": {
            "@type": "Place",
            "name": city["vi"],
            "alternateName": city["en"],
            "address": {"@type": "PostalAddress", "addressCountry": city["country_code"]},
            "geo": {
                "@type": "GeoCoordinates",
                "latitude": city["latitude"],
                "longitude": city["longitude"],
            },
        },
        "breadcrumb": {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Weather History", "item": SITE_URL},
                {"@type": "ListItem", "position": 2, "name": city["vi"], "item": url},
            ],
        },
    }


def city_index(cities: list[dict[str, Any]], prefix: str) -> str:
    def links(group: str) -> str:
        items = [
            f'<li><a href="{prefix}{c["slug"]}/">{html.escape(c["vi"])}</a></li>'
            for c in cities
            if c["group"] == group
        ]
        return "\n          ".join(items)

    return f"""<details class="city-index">
        <summary data-i18n="footer.cities">Các thành phố</summary>
        <h2 data-i18n="footer.vietnam">Việt Nam</h2>
        <ul>
          {links("vietnam")}
        </ul>
        <h2 data-i18n="footer.world">Thế giới</h2>
        <ul>
          {links("world")}
        </ul>
      </details>"""


def render(template: str, cities: list[dict[str, Any]], city: dict[str, Any] | None) -> str:
    page = template
    if city is None:
        prefix = "./"
        page = SEO_BLOCK.sub(
            lambda _: seo_block(
                title=ROOT_TITLE, description=ROOT_DESCRIPTION, url=SITE_URL, ld=root_ld()
            ),
            page,
        )
    else:
        prefix = "../"
        place = place_vi(city)
        title = CITY_TITLE.format(place=place)
        description = CITY_DESCRIPTION.format(place=place)
        url = f"{SITE_URL}{city['slug']}/"
        block = seo_block(
            title=title,
            description=description,
            url=url,
            ld=city_ld(city, title, description, url),
        )
        page = SEO_BLOCK.sub(lambda _: block, page)
        # Assets and links are relative to the site root, one level up.
        page = page.replace('href="./', 'href="../').replace('src="./', 'src="../')
        page = page.replace('data-root="./"', 'data-root="../"')
        city_json = json.dumps(city, ensure_ascii=False).replace("</", "<\\/")
        page = page.replace(PAGE_CITY, PAGE_CITY.replace(">null<", f">{city_json}<"))
        # Crawlable, city-specific text before any JavaScript runs.
        page = page.replace(
            '<h2 id="place-title" class="page-title"></h2>',
            f'<h2 id="place-title" class="page-title">{html.escape(place)}</h2>',
        )
        page = re.sub(
            r'(<p id="page-intro" class="page-intro">).*?(</p>)',
            lambda m: f"{m.group(1)}{html.escape(description)}{m.group(2)}",
            page,
            flags=re.S,
        )
    return page.replace(CITY_INDEX, city_index(cities, prefix))


def sitemap(cities: list[dict[str, Any]], lastmod: str) -> str:
    urls = [SITE_URL] + [f"{SITE_URL}{c['slug']}/" for c in cities]
    body = "\n".join(
        f"  <url>\n    <loc>{u}</loc>\n    <lastmod>{lastmod}</lastmod>\n  </url>" for u in urls
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{body}\n</urlset>\n"
    )


def not_found_page(base_path: str) -> str:
    base = json.dumps(base_path)
    return f"""<!doctype html>
<html lang="vi">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="robots" content="noindex" />
    <title>Không tìm thấy trang | Weather History</title>
    <script>
      // /<base>/some-place/ → search for "some place" on the app's root page.
      (function () {{
        var base = {base};
        var path = decodeURIComponent(location.pathname);
        if (path.indexOf(base) !== 0) return;
        var rest = path.slice(base.length).replace(/\\/(index\\.html)?$/, "");
        if (rest && rest.indexOf("/") === -1) {{
          location.replace(base + "?location=" + encodeURIComponent(rest.replace(/-/g, " ")));
        }}
      }})();
    </script>
  </head>
  <body style="font-family: system-ui, sans-serif; text-align: center; padding: 48px 16px">
    <h1>Không tìm thấy trang · Page not found</h1>
    <p><a href="{html.escape(base_path)}">Lịch sử Thời tiết · Weather History</a></p>
  </body>
</html>
"""


def build(src: Path, out: Path, *, base_path: str = "/weahist/", lastmod: str | None = None) -> int:
    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(src, out)
    cities: list[dict[str, Any]] = json.loads((src / "cities.json").read_text(encoding="utf-8"))
    template = (src / "index.html").read_text(encoding="utf-8")
    if not SEO_BLOCK.search(template) or PAGE_CITY not in template or CITY_INDEX not in template:
        raise SystemExit("web/index.html is missing a build placeholder")

    (out / "index.html").write_text(render(template, cities, None), encoding="utf-8")
    for city in cities:
        page_dir = out / city["slug"]
        page_dir.mkdir()
        (page_dir / "index.html").write_text(render(template, cities, city), encoding="utf-8")
    (out / "sitemap.xml").write_text(
        sitemap(cities, lastmod or date.today().isoformat()), encoding="utf-8"
    )
    (out / "404.html").write_text(not_found_page(base_path), encoding="utf-8")
    stamp_service_worker(out)
    return len(cities)


def stamp_service_worker(out: Path) -> None:
    """Version the service worker's caches by the content of the whole site."""
    sw = out / "sw.js"
    digest = hashlib.sha256()
    for path in sorted(p for p in out.rglob("*") if p.is_file() and p != sw):
        digest.update(path.relative_to(out).as_posix().encode())
        digest.update(path.read_bytes())
    source = sw.read_text(encoding="utf-8")
    if 'const BUILD_ID = "dev";' not in source:
        raise SystemExit("web/sw.js is missing its BUILD_ID placeholder")
    sw.write_text(
        source.replace('const BUILD_ID = "dev";', f'const BUILD_ID = "{digest.hexdigest()[:12]}";'),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--src", type=Path, default=ROOT / "web")
    parser.add_argument("--out", type=Path, default=ROOT / "_site")
    parser.add_argument("--base-path", default="/weahist/", help="URL path the site is served at")
    args = parser.parse_args()
    n = build(args.src, args.out, base_path=args.base_path)
    print(f"built {args.out} with {n} city pages")


if __name__ == "__main__":
    main()
